# Streamlit secrets configuration
# This file is used for environment variables and sensitive configuration

# AI Model Configuration
[ai_models]
cache_dir = "./models"
use_gpu = false
max_memory = "4GB"

# Application Settings
[app]
max_file_size = 100
supported_formats = ["png", "jpg", "jpeg", "webp"]
debug_mode = false

# Performance Settings
[performance]
enable_caching = true
cache_ttl = 3600
max_workers = 2 